//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using Leap;
namespace AssemblyCSharp
{	
	public class LeapBehavior : MonoBehaviour {
		Controller controller;
		
		void Start ()
		{
			controller = new Controller();
		}
		
		void Update ()
		{
			print ("ok");
		}
	}
}

